import Head from "next/head";
import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";

// Ui - Components
const Container = dynamic(() => import("@components/Container"));

// Layouts
import FromCreators from "@layouts/FromCreator";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Container className="flex flex-col">
          {/* From Creators */}
          <FromCreators />
        </Container>
      </div>
    </>
  );
};

export default Home;
